Various changes; remove YCM for golang, etc

diff --git a/COMMON/.bin/_install_vim b/COMMON/.bin/_install_vim
--- a/COMMON/.bin/_install_vim
+++ b/COMMON/.bin/_install_vim
@@ -1,4 +1,4 @@
-#!/bin/bash
+#! /bin/bash
 #
 # Install vim with clipboard and python3 support from source
 # This script was developed within the docker image myubuntu18.04
@@ -26,32 +26,37 @@ sleep 3
 
 ### If sudo user, install all dependencies
 if _is_user_sudoer; then
-    echo -e """
+  echo -e """
     You have sudo permissions; let's use them to install dependencies for vim!
     """
-    sleep 1
-    sudo apt update -y
-    sudo apt upgrade -y
-    sudo apt install build-essential \
-        man \
-        manpages-dev \
-        git \
-        curl \
-        cmake \
-        python \
-        python3 \
-        python-dev \
-        python3-dev \
-        python3-pip \
-        libx11-6 \
-        libx11-dev \
-        libxtst-dev \
-        libxt-dev \
-        libsm-dev \
-        libevent-dev \
-        libncurses5-dev \
-        libncurses5 \
-        libxpm-dev
+  sleep 1
+  sudo apt update -y
+  sudo apt upgrade -y
+  sudo apt install build-essential \
+    man \
+    manpages-dev \
+    git \
+    curl \
+    cmake \
+    python \
+    python3 \
+    python-dev \
+    python3-dev \
+    python3-pip \
+    libx11-6 \
+    libx11-dev \
+    libxtst-dev \
+    libxt-dev \
+    libsm-dev \
+    libevent-dev \
+    libncurses5-dev \
+    libncurses5 \
+    libxpm-dev
+else
+  echo -e """
+    You do not have sudo permissions; let's just hope that this machine has all of the prerequisite libraries!
+    """
+  sleep 1
 fi
 
 ### Need to make sure we have the right python libs for our installations
@@ -87,24 +92,24 @@ PYTHON2_BINARY=$(which python2)
 
 # Centos8
 # Trickier to find automatedly, so set explicitly
-if [[ $(cat /etc/os-release 2>/dev/null | grep 'CentOS Linux 8' | wc -l) -eq 1 ]]; then
+if _is_centos8; then
+  PYTHON2_CONFIG_DIR="/usr/lib64/python2.7/config"
+  PYTHON3_CONFIG_DIR="/usr/lib64/python3.6/config-3.6m-x86_64-linux-gnu"
+
+  # Specify path to python3 binary corresponding to PYTHON3_CONFIG_DIR
+  PYTHON3_BINARY="/usr/bin/python3"
+
+  ### If you're on centos8 and don't have sudo permissions, you might need
+  ### to manually install packages through the yusr tool;
+  ### if so, you might need to also alter the make-config paths
+  ### to look for resources within .myfs
+  if ! _is_user_sudoer; then
+    yusr install python2-devel
     PYTHON2_CONFIG_DIR="/usr/lib64/python2.7/config"
-    PYTHON3_CONFIG_DIR="/usr/lib64/python3.6/config-3.6m-x86_64-linux-gnu"
-
-    # Specify path to python3 binary corresponding to PYTHON3_CONFIG_DIR
-    PYTHON3_BINARY="/usr/bin/python3"
-
-    ### If you're on centos8 and don't have sudo permissions, you might need
-    ### to manually install packages through the yusr tool;
-    ### if so, you might need to also alter the make-config paths
-    ### to look for resources within .myfs
-    if ! _is_user_sudoer; then
-        yusr install python2-devel
-        PYTHON2_CONFIG_DIR="/usr/lib64/python2.7/config"
-        PYTHON2_CONFIG_DIR="$HOME/.myfs/usr/lib64/python2.7/config"
-        PYTHON2_BINARY=$(which python2)
-        cflags="-I$HOME/.myfs/usr/include/python2.7"
-    fi
+    PYTHON2_CONFIG_DIR="$HOME/.myfs/usr/lib64/python2.7/config"
+    PYTHON2_BINARY=$(which python2)
+    cflags="-I$HOME/.myfs/usr/include/python2.7"
+  fi
 
 fi
 
@@ -112,21 +117,21 @@ fi
 ### NOTE:   this is a necessary nut not sufficient condition;
 ###         the config dir also needs various lib files
 [[ ! -f "$PYTHON2_CONFIG_DIR/Makefile" ]] &&
-    echo "Can't find $PYTHON2_CONFIG_DIR/Makefile ...exiting." &&
-    exit 1
+  echo "Can't find $PYTHON2_CONFIG_DIR/Makefile ...exiting." &&
+  exit 1
 
 [[ ! -f "$PYTHON3_CONFIG_DIR/Makefile" ]] &&
-    echo "Can't find $PYTHON3_CONFIG_DIR/Makefile ...exiting." &&
-    exit 1
+  echo "Can't find $PYTHON3_CONFIG_DIR/Makefile ...exiting." &&
+  exit 1
 
 ### Vim Requires ncurses
 if [[ $1 == '--with-ncurses' ]]; then
-    echo "Installing ncurses to .myfs"
-    sleep 2
-    _install_ncurses
+  echo "Installing ncurses to .myfs"
+  sleep 2
+  _install_ncurses
 else
-    echo "Skipping ncurses from source..."
-    sleep 2
+  echo "Skipping ncurses from source..."
+  sleep 2
 fi
 
 ### Build vim from source
@@ -166,21 +171,21 @@ sleep 5
 
 ### Begin actual build from source
 BEGINCONFIG=true \
-    CFLAGS="$cflags" \
-    LDFLAGS="-L$HOME/.myfs/usr/local/lib" \
-    LD_LIBRARY_PATH="$HOME/.myfs/usr/local/lib" ./configure \
-    --with-x \
-    --enable-gui="auto" \
-    --enable-gtk2-check \
-    --enable-pythoninterp="yes" \
-    --with-python-command="$PYTHON2_BINARY" \
-    --with-python-config-dir="$PYTHON2_CONFIG_DIR" \
-    --enable-python3interp="yes" \
-    --with-python3-command="$PYTHON3_BINARY" \
-    --with-python3-config-dir="$PYTHON3_CONFIG_DIR" \
-    --enable-fail-if-missing \
-    --prefix="$HOME/.myfs/usr/local" \
-    --with-local-dir="$HOME/.myfs/usr"
+  CFLAGS="$cflags" \
+  LDFLAGS="-L$HOME/.myfs/usr/local/lib" \
+  LD_LIBRARY_PATH="$HOME/.myfs/usr/local/lib" ./configure \
+  --with-x \
+  --enable-gui="auto" \
+  --enable-gtk2-check \
+  --enable-pythoninterp="yes" \
+  --with-python-command="$PYTHON2_BINARY" \
+  --with-python-config-dir="$PYTHON2_CONFIG_DIR" \
+  --enable-python3interp="yes" \
+  --with-python3-command="$PYTHON3_BINARY" \
+  --with-python3-config-dir="$PYTHON3_CONFIG_DIR" \
+  --enable-fail-if-missing \
+  --prefix="$HOME/.myfs/usr/local" \
+  --with-local-dir="$HOME/.myfs/usr"
 
 make
 make install
@@ -189,11 +194,11 @@ cd $previous_dir
 
 ### Check if vim is now installed to .myfs
 if [[ $(which vim | grep myfs | wc -l) -ge 1 ]]; then
-    ### Now that vim is installed, let's download vundle plugins
-    echo -e "${GRE}Vim installed; now re-downloading vundle plugins${WHI}"
-    _install_vundle_plugins
+  ### Now that vim is installed, let's download vundle plugins
+  echo -e "${GRE}Vim installed; now re-downloading vundle plugins${WHI}"
+  _install_vundle_plugins
 else
-    echo -e """${RED}
+  echo -e """${RED}
     Vim is not installed. Something must have gone wrong.
     ${WHI}"""
 fi
diff --git a/COMMON/.bin/_install_ycm b/COMMON/.bin/_install_ycm
--- a/COMMON/.bin/_install_ycm
+++ b/COMMON/.bin/_install_ycm
@@ -13,25 +13,25 @@ command -v python3 >/dev/null 2>&1 || (echo "python3 not found" && exit 1)
 
 ### If cmake doesn't exist, install it with python3
 if ! $(command -v cmake >/dev/null 2>&1); then
-    command -v pip3 >/dev/null 2>&1 || (echo "pip3 not found" && exit 1)
-    python3 -m pip install --user cmake
+  command -v pip3 >/dev/null 2>&1 || (echo "pip3 not found" && exit 1)
+  python3 -m pip install --user cmake
 fi
 
 ### If Ubuntu18, then we need to install g++-8
 if _is_ubuntu18; then
-    ### Check if g++-8 is installed
-    if $(command -v g++-8 >/dev/null 2>&1); then
-        cxx=$(which g++-8)
-    elif _is_user_sudoer; then
-        sudo apt install -y g++-8
-        cxx=$(which g++-8)
-    else
-        msg=""
-        msg+="${RED}Sorry - you are on Ubuntu18 without g++-8${WHI}"
-        msg+="${RED} or sudo permissions${WHI}"
-        echo -e "$msg"
-        exit 1
-    fi
+  ### Check if g++-8 is installed
+  if $(command -v g++-8 >/dev/null 2>&1); then
+    cxx=$(which g++-8)
+  elif _is_user_sudoer; then
+    sudo apt install -y g++-8
+    cxx=$(which g++-8)
+  else
+    msg=""
+    msg+="${RED}Sorry - you are on Ubuntu18 without g++-8${WHI}"
+    msg+="${RED} or sudo permissions${WHI}"
+    echo -e "$msg"
+    exit 1
+  fi
 fi
 
 ### Rerun ycm-install process manually
@@ -39,7 +39,14 @@ previous_dir=$PWD
 cd $HOME/.vim/bundle/YouCompleteMe
 git pull origin master
 git submodule update --init --recursive
-CXX=$cxx python3 install.py --all
+### Only install completers that I use to code
+# CXX=$cxx python3 install.py --all
+CXX=$cxx python3 install.py --clang-completer --ts-completer
+#--cs-completer
+#--go-completer
+#--rust-completer
+#--java-completer
+#--ts-completer
 
 echo -e "echo '''\033[31m
 ====================================
diff --git a/myconfig b/myconfig
--- a/myconfig
+++ b/myconfig
@@ -8,75 +8,75 @@ skip_confirmation=false
 # Define aux functions
 function _usage() {
 
-    local msg=""
-    msg+="${WHI}Usage: ${GRE}myconfig ${CYA}<command> [<args>]\n${WHI}"
-    msg+="\n"
-    msg+="${CYA}help                ${WHI}Print usage of myconfig\n${WHI}"
-    msg+="${CYA}version             ${WHI}Print version\n${WHI}"
-    msg+="${CYA}status              ${WHI}Shows installation status of myconfig\n${WHI}"
-    msg+="${CYA}install [-y] <arg>  ${WHI}Install <arg> from source [confirmed]\n${WHI}"
-    msg+="${CYA}update [-y]         ${WHI}Update myconfig [confirmed]\n${WHI}"
-    echo -e "$msg"
+  local msg=""
+  msg+="${WHI}Usage: ${GRE}myconfig ${CYA}<command> [<args>]\n${WHI}"
+  msg+="\n"
+  msg+="${CYA}help                ${WHI}Print usage of myconfig\n${WHI}"
+  msg+="${CYA}version             ${WHI}Print version\n${WHI}"
+  msg+="${CYA}status              ${WHI}Shows installation status of myconfig\n${WHI}"
+  msg+="${CYA}install [-y] <arg>  ${WHI}Install <arg> from source [confirmed]\n${WHI}"
+  msg+="${CYA}update [-y]         ${WHI}Update myconfig [confirmed]\n${WHI}"
+  echo -e "$msg"
 }
 
 function _install_usage() {
 
-    local msg=""
-    msg+="${WHI}Usage: ${GRE}myconfig install ${CYA}[-y] <command>${WHI}\n"
-    msg+="\n"
-    msg+="${CYA}self        ${WHI}Permanently install myconfig to ~/.myconfig${WHI}\n"
-    msg+="${CYA}vim         ${WHI}Install vim 8.2 from source${WHI}\n"
-    msg+="${CYA}tmux        ${WHI}Install tmux 3.1b from source${WHI}\n"
-    msg+="${CYA}zsh         ${WHI}Install zsh 5.7.1 from source${WHI}\n"
-    msg+="${CYA}prometheus  ${WHI}Install prometheus from source${WHI}\n"
-    echo -e "$msg"
+  local msg=""
+  msg+="${WHI}Usage: ${GRE}myconfig install ${CYA}[-y] <command>${WHI}\n"
+  msg+="\n"
+  msg+="${CYA}self        ${WHI}Permanently install myconfig to ~/.myconfig${WHI}\n"
+  msg+="${CYA}vim         ${WHI}Install vim 8.2 from source${WHI}\n"
+  msg+="${CYA}tmux        ${WHI}Install tmux 3.1b from source${WHI}\n"
+  msg+="${CYA}zsh         ${WHI}Install zsh 5.7.1 from source${WHI}\n"
+  msg+="${CYA}all         ${WHI}Install zsh, npm, vim & tmux${WHI}\n"
+  echo -e "$msg"
 }
 
 function _create_myfs() {
 
-    if [[ -d $HOME/.myfs ]]; then
-        echo -e "${RED}~/.myfs already exists"
-        return 1
-    else
-        echo -e "${GRE}Creating ~/.myfs"
-        local msg=""
-        msg+="# What's This?\n"
-        msg+=""
-        msg+="This is a dir for a filesystem structure for building/installing "
-        msg+="executables from source using the myconfig CLI"
-        mkdir $HOME/.myfs && echo $msg >>$HOME/.myfs/README.md
-    fi
+  if [[ -d $HOME/.myfs ]]; then
+    echo -e "${RED}~/.myfs already exists"
+    return 1
+  else
+    echo -e "${GRE}Creating ~/.myfs"
+    local msg=""
+    msg+="# What's This?\n"
+    msg+=""
+    msg+="This is a dir for a filesystem structure for building/installing "
+    msg+="executables from source using the myconfig CLI"
+    mkdir $HOME/.myfs && echo $msg >>$HOME/.myfs/README.md
+  fi
 }
 
 function _update_myconfig() {
 
-    # Exit if not fully installed
-    if ! _is_myconfig_fully_installed; then
-        echo -e "${RED}myconfig is not installed${WHI}"
-        return 1
-    fi
+  # Exit if not fully installed
+  if ! _is_myconfig_fully_installed; then
+    echo -e "${RED}myconfig is not installed${WHI}"
+    return 1
+  fi
 
-    # Exit if this is the "SSOT" repo
-    if [[ -f $HOME/.myconfig/.SSOT ]]; then
-        echo -e """${RED}
+  # Exit if this is the "SSOT" repo
+  if [[ -f $HOME/.myconfig/.SSOT ]]; then
+    echo -e """${RED}
         This is the SSOT repo; it will NOT update via the myconfig LCI!
         ${WHI}"""
-        return 1
-    fi
+    return 1
+  fi
 
-    # Perform update from remote
-    local previous_dir=$PWD
-    cd $HOME/.myconfig/
-    git fetch origin
-    git checkout master
-    git reset --hard origin/master
-    cd $previous_dir
+  # Perform update from remote
+  local previous_dir=$PWD
+  cd $HOME/.myconfig/
+  git fetch origin
+  git checkout master
+  git reset --hard origin/master
+  cd $previous_dir
 
-    # Update vundle plugins
-    #_install_vundle_plugins
+  # Update vundle plugins
+  #_install_vundle_plugins
 
-    # Finish
-    echo -e """${GRE}
+  # Finish
+  echo -e """${GRE}
     =================
     Update completed!
     =================
@@ -86,175 +86,189 @@ function _update_myconfig() {
 
 function _fully_install_myconfig() {
 
-    if _is_myconfig_fully_installed; then
-        echo -e "${RED}myconfig is already installed${WHI}"
-        return 1
-    fi
+  if _is_myconfig_fully_installed; then
+    echo -e "${RED}myconfig is already installed${WHI}"
+    return 1
+  fi
 
-    if [[ $skip_confirmation == false ]]; then
-        local msg=""
-        msg+="${RED} Are you sure you want to install "
-        msg+="myconfig to ${WHI}$HOME/.myconfig?${RED} (y/N)\n"
-        echo -e "$msg"
-        read choice
-        # Exit unless choice is 'y' or 'Y'
-        if [[ ! $choice =~ ^y$|^Y$ ]]; then
-            echo -e "${RED}Exiting...${WHI}"
-            return 1
-        fi
-    fi
-
-    echo -e "${GRE}OK, let's fully install myconfig...${WHI}"
-    sleep 2
-    _create_myfs
-    local previous_dir=$PWD
-    cd $HOME
-    git clone https://github.com/d-w-d/myconfig.git .myconfig
-    cd $previous_dir
-
-    ### Replace .rcfiles
-    _replace_dotrc_files
-
-    ### Remove /tmp/myconfig, it will still use this if you forget to re-source
-    ! $_is_installing_vundle_plugins && rm -rf /tmp/myconfig
-
-    ### Final message
+  if [[ $skip_confirmation == false ]]; then
     local msg=""
-    msg+="${GRE}Installation complete! ${WHI}"
-    msg+="${GRE}Run ${CYA}'source ~/.myconfig/entry.sh' ${WHI}"
-    msg+="${GRE}to activate changes. ${WHI}"
+    msg+="${RED} Are you sure you want to install "
+    msg+="myconfig to ${WHI}$HOME/.myconfig?${RED} (y/N)\n"
     echo -e "$msg"
+    read choice
+    # Exit unless choice is 'y' or 'Y'
+    if [[ ! $choice =~ ^y$|^Y$ ]]; then
+      echo -e "${RED}Exiting...${WHI}"
+      return 1
+    fi
+  fi
+
+  echo -e "${GRE}OK, let's fully install myconfig...${WHI}"
+  sleep 2
+  _create_myfs
+  local previous_dir=$PWD
+  cd $HOME
+  git clone https://github.com/d-w-d/myconfig.git .myconfig
+  cd $previous_dir
+
+  ### Replace .rcfiles
+  _replace_dotrc_files
+
+  ### Remove /tmp/myconfig, it will still use this if you forget to re-source
+  ! $_is_installing_vundle_plugins && rm -rf /tmp/myconfig
+
+  ### Final message
+  local msg=""
+  msg+="${GRE}Installation complete! ${WHI}"
+  msg+="${GRE}Run ${CYA}'source ~/.myconfig/entry.sh' ${WHI}"
+  msg+="${GRE}to activate changes. ${WHI}"
+  echo -e "$msg"
 }
 
 function _status() {
 
-    local msg="${WHI}Myconfig status: \n${WHI}"
+  local msg="${WHI}Myconfig status: \n${WHI}"
 
-    # Test if myconfig is installed
-    if _is_myconfig_fully_installed; then
-        msg+="${GRE}✓ myconfig is fully installed\n${WHI}"
-    else
-        msg+="${RED}✗ myconfig is NOT fully installed\n${WHI}"
-    fi
+  # Test if myconfig is installed
+  if _is_myconfig_fully_installed; then
+    msg+="${GRE}✓ myconfig is fully installed\n${WHI}"
+  else
+    msg+="${RED}✗ myconfig is NOT fully installed\n${WHI}"
+  fi
 
-    # Test if vim has been installed to .myfs
-    if [[ $(which -a vim | grep $HOME/.myfs | wc -l) -gt 0 ]]; then
-        msg+="${GRE}✓ myconfig > vim is installed\n${WHI}"
-    else
-        msg+="${RED}✗ myconfig > vim is NOT installed\n${WHI}"
-    fi
+  # Test if vim has been installed to .myfs
+  if [[ $(which -a vim | grep $HOME/.myfs | wc -l) -gt 0 ]]; then
+    msg+="${GRE}✓ myconfig > vim is installed\n${WHI}"
+  else
+    msg+="${RED}✗ myconfig > vim is NOT installed\n${WHI}"
+  fi
 
-    # Test if tmux has been installed to .myfs
-    if [[ $(which -a tmux | grep $HOME/.myfs | wc -l) -gt 0 ]]; then
-        msg+="${GRE}✓ myconfig > tmux is installed\n${WHI}"
-    else
-        msg+="${RED}✗ myconfig > tmux is NOT installed\n${WHI}"
-    fi
+  # Test if tmux has been installed to .myfs
+  if [[ $(which -a tmux | grep $HOME/.myfs | wc -l) -gt 0 ]]; then
+    msg+="${GRE}✓ myconfig > tmux is installed\n${WHI}"
+  else
+    msg+="${RED}✗ myconfig > tmux is NOT installed\n${WHI}"
+  fi
 
-    echo -e "$msg"
+  echo -e "$msg"
 }
 
 main() {
 
-    ### Handle no args
-    if [[ $# -eq 0 ]]; then
-        _usage
-        return 1
-    fi
+  ### Handle no args
+  if [[ $# -eq 0 ]]; then
+    _usage
+    return 1
+  fi
 
-    ### Main Loop
-    while [[ $# -gt 0 ]]; do
-        arg1=$1
+  ### Main Loop
+  while [[ $# -gt 0 ]]; do
+    arg1=$1
+    shift # expose next argument
+    case "$arg1" in
+    "--help" | "help")
+      _usage
+      break
+      ;;
+    "--version" | "version")
+      _version
+      break
+      ;;
+    "--status" | "status")
+      _status
+      break
+      ;;
+    "update")
+      _update_myconfig
+      break
+      ;;
+    "install")
+      # Handle no further install args
+      [[ $# -eq 0 ]] && _install_usage && return 1
+
+      # Handle further install args
+      while [[ $# -gt 0 ]]; do
+        arg2="$1"
         shift # expose next argument
-        case "$arg1" in
+        case "$arg2" in
         "--help" | "help")
-            _usage
-            break
-            ;;
-        "--version" | "version")
-            _version
-            break
-            ;;
-        "--status" | "status")
-            _status
-            break
-            ;;
-        "update")
-            _update_myconfig
-            break
-            ;;
-        "install")
-            # Handle no further install args
-            [[ $# -eq 0 ]] && _install_usage && return 1
-
-            # Handle further install args
-            while [[ $# -gt 0 ]]; do
-                arg2="$1"
-                shift # expose next argument
-                case "$arg2" in
-                "--help" | "help")
-                    _install_usage
-                    break
-                    ;;
-                "-y")
-                    skip_confirmation=true
-                    ;;
-                "self")
-                    _fully_install_myconfig
-                    return $?
-                    break
-                    ;;
-                "vim")
-                    if _is_myconfig_fully_installed; then
-                        _install_vim
-                    else
-                        local msg=""
-                        msg+="${RED}You must fully install myconfig ${WHI}"
-                        msg+="${RED}before installing vim${WHI}"
-                        echo -e "$msg"
-                    fi
-                    break
-                    ;;
-                "tmux")
-                    if _is_myconfig_fully_installed; then
-                        _install_tmux
-                    else
-                        local msg=""
-                        msg+="${RED}You must fully install myconfig ${WHI}"
-                        msg+="${RED}before installing tmux${WHI}"
-                        echo -e "$msg"
-                    fi
-                    break
-                    ;;
-                "zsh")
-                    if _is_myconfig_fully_installed; then
-                        _install_zsh
-                    else
-                        local msg=""
-                        msg+="${RED}You must fully install myconfig ${WHI}"
-                        msg+="${RED}before installing zsh${WHI}"
-                        echo -e "$msg"
-                    fi
-                    break
-                    ;;
-                *)
-                    echo >&2 "Invalid option: $@"
-                    echo "INSTALL CALLED BARE"
-                    _install_usage
-                    return 1
-                    ;;
-                esac
-            done
-            break
-            ;;
-
+          _install_usage
+          break
+          ;;
+        "-y")
+          skip_confirmation=true
+          ;;
+        "self")
+          _fully_install_myconfig
+          return $?
+          break
+          ;;
+        "all")
+          if _is_myconfig_fully_installed; then
+            _install_zsh
+            nvm install 18
+            _install_vim
+            _install_tmux
+          else
+            local msg=""
+            msg+="${RED}You must fully install myconfig ${WHI}"
+            msg+="${RED}before installing tmux${WHI}"
+            echo -e "$msg"
+          fi
+          break
+          ;;
+        "vim")
+          if _is_myconfig_fully_installed; then
+            _install_vim
+          else
+            local msg=""
+            msg+="${RED}You must fully install myconfig ${WHI}"
+            msg+="${RED}before installing vim${WHI}"
+            echo -e "$msg"
+          fi
+          break
+          ;;
+        "tmux")
+          if _is_myconfig_fully_installed; then
+            _install_tmux
+          else
+            local msg=""
+            msg+="${RED}You must fully install myconfig ${WHI}"
+            msg+="${RED}before installing tmux${WHI}"
+            echo -e "$msg"
+          fi
+          break
+          ;;
+        "zsh")
+          if _is_myconfig_fully_installed; then
+            _install_zsh
+          else
+            local msg=""
+            msg+="${RED}You must fully install myconfig ${WHI}"
+            msg+="${RED}before installing zsh${WHI}"
+            echo -e "$msg"
+          fi
+          break
+          ;;
         *)
-            echo >&2 "Invalid option: $@"
-            _usage
-            return 1
-            ;;
+          echo >&2 "Invalid option: $@"
+          echo "INSTALL CALLED BARE"
+          _install_usage
+          return 1
+          ;;
         esac
-    done
+      done
+      break
+      ;;
+
+    *)
+      echo >&2 "Invalid option: $@"
+      _usage
+      return 1
+      ;;
+    esac
+  done
 }
 
 ### Execute main with all arguments passed to script
